### ISSUE TITLE
Análise do código

### ISSUE THREAD

**Issue by AlyoshaS** [w-lopes/taller-test#16]
Olá @w-lopes!

Estou aqui para avisar que recebemos o seu teste e vamos fazer análise do código através de issues do github. Seu teste vai ser analisado por no mínimo três desenvolvedores que podem ter perguntas ou não.

Abraço!

**Comment by w-lopes** [comment]
> Olá @w-lopes!
> 
> Estou aqui para avisar que recebemos o seu teste e vamos fazer análise do código através de issues do github. Seu teste vai ser analisado por no mínimo três desenvolvedores que podem ter perguntas ou não.
> 
> Abraço!

Certo, fico no aguardo :)
