### ISSUE TITLE
#8 - Focos nas mensagens recentes

### ISSUE THREAD

**Issue by rrmontuan** [w-lopes/taller-test#17]
Fala Wellington, tudo certo? 

Primeiramente, gostaria de parabenizá-lo por ter realizado boa parte das tarefas do board. Feito isso, acho que a Evelyn já havia dito que eventualmente poderiam aparecer algumas perguntas. São perguntas apenas pra ver como você chegou naquele resultado, se poderia ser implementado de outra maneira, ou seja, são perguntas bem tranquilas e sem pressão alguma. =)

Na implementação do item **#8 (Foco nas mensagens recentes)**, observei nesse [trecho](https://github.com/w-lopes/taller-test/blob/255f1365944a98e46df5500d4c07e62ac0cafeed/next/pages/channel.js#L205) que a função que realiza o scroll da página é executada para todas as mensagens.

Você conseguiria pensar em uma outra implementação que não necessitasse executar a função pra cada mensagem?

**Comment by w-lopes** [comment]
> Fala Wellington, tudo certo?
> 
> Primeiramente, gostaria de parabenizá-lo por ter realizado boa parte das tarefas do board. Feito isso, acho que a Evelyn já havia dito que eventualmente poderiam aparecer algumas perguntas. São perguntas apenas pra ver como você chegou naquele resultado, se poderia ser implementado de outra maneira, ou seja, são perguntas bem tranquilas e sem pressão alguma. =)
> 
> Na implementação do item **#8 (Foco nas mensagens recentes)**, observei nesse [trecho](https://github.com/w-lopes/taller-test/blob/255f1365944a98e46df5500d4c07e62ac0cafeed/next/pages/channel.js#L205) que a função que realiza o scroll da página é executada para todas as mensagens.
> 
> Você conseguiria pensar em uma outra implementação que não necessitasse executar a função pra cada mensagem?

@rrmontuan, tudo certo...
OK, vou ver aqui e já te retorno com o resultado :)

**Comment by rrmontuan** [comment]
Tranquilo, @w-lopes. Vai na boa ai hehe

**Comment by w-lopes** [comment]
> Tranquilo, @w-lopes. Vai na boa ai hehe

Feito!
Aqui a [alteração no arquivo](https://github.com/w-lopes/taller-test/commit/f0ad86b84ec6a30ed9a146ea244c93eb63a664d9). Falha minha, realmente o ideal é carregar apenas uma vez "^^.
Alterei também a coleta do elemento pelo JS, assim ele busca apenas uma vez.

**Comment by rrmontuan** [comment]
show, ficou bacana Wellington. Outra alternativa seria usar o lifecycle do react, possivelmente o componentDidMount (nessa versão de react do projeto).

**Comment by w-lopes** [comment]
> show, ficou bacana Wellington. Outra alternativa seria usar o lifecycle do react, possivelmente o componentDidMount (nessa versão de react do projeto).

Opa @rrmontuan 

Confesso que não sou muito do React ainda, após as aulas e exemplos que fiz, esse projeto foi o primeiro que trabalhei com ele. Mas essa dica vai pro repertório, valeu! :D
